local UnitDef = {}

UnitDef.BULLET_CATEGORY_MASK = 0x0001
UnitDef.BULLET_CONTACT_TEST_MASK = 0x0001
UnitDef.BULLET_COLLISION_MASK = 0x0010

UnitDef.BOARDER_CATEGORY_MASK = 0x0010
UnitDef.BOARDER_CONTACT_TEST_MASK = 0x0001
UnitDef.BOARDER_COLLISION_MASK = 0x0001

UnitDef.BULLET_TAG = 1
UnitDef.BOARDER_TAG = 2
UnitDef.ICECUBE_TAG = 3

return UnitDef