local UnitDef = {}

UnitDef.BULLET_CATEGORY_MASK = 0x0001
UnitDef.BULLET_CONTACT_TEST_MASK = 0x0001
UnitDef.BULLET_COLLISION_MASK = 0x0010

UnitDef.BOARDER_CATEGORY_MASK = 0x0010
UnitDef.BOARDER_CONTACT_TEST_MASK = 0x0001
UnitDef.BOARDER_COLLISION_MASK = 0x0001

UnitDef.BULLET_TAG = 1
UnitDef.BOARDER_TAG = 2
UnitDef.ICECUBE_TAG = 3

UnitDef.GAME_COLLISION_X = 18
UnitDef.GAME_COLLISION_Y = 18
UnitDef.GAME_COLLISION_HEIGHT = 537
UnitDef.GAME_COLLISION_WIDTH = 888

UnitDef.BOARDER_TOP = 1
UnitDef.BOARDER_BOTTOM = 2
UnitDef.BOARDER_LEFT = 3
UnitDef.BOARDER_RIGHT = 4

UnitDef.STATION_READY = 1
UnitDef.STATION_SHOOT = 2

return UnitDef